// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/proto/mesh.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeshControl_StreamConfig_FullMethodName  = "/mesh.MeshControl/StreamConfig"
	MeshControl_RegisterProxy_FullMethodName = "/mesh.MeshControl/RegisterProxy"
)

// MeshControlClient is the client API for MeshControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MeshControl is the service that manages the data plane proxies
// Control Plane implements this server
// Data Plane proxies are clients
type MeshControlClient interface {
	// StreamConfig establishes a long-lived connection between proxy and control plane
	// The proxy sends its info, and the control plane streams config updates
	// This is a SERVER STREAMING RPC - server sends multiple messages
	StreamConfig(ctx context.Context, in *ProxyInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdate], error)
	// RegisterProxy allows a proxy to register itself with the control plane
	// This is a UNARY RPC - single request, single response
	RegisterProxy(ctx context.Context, in *ProxyInfo, opts ...grpc.CallOption) (*RegistrationResponse, error)
}

type meshControlClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshControlClient(cc grpc.ClientConnInterface) MeshControlClient {
	return &meshControlClient{cc}
}

func (c *meshControlClient) StreamConfig(ctx context.Context, in *ProxyInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MeshControl_ServiceDesc.Streams[0], MeshControl_StreamConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProxyInfo, ConfigUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshControl_StreamConfigClient = grpc.ServerStreamingClient[ConfigUpdate]

func (c *meshControlClient) RegisterProxy(ctx context.Context, in *ProxyInfo, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, MeshControl_RegisterProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshControlServer is the server API for MeshControl service.
// All implementations must embed UnimplementedMeshControlServer
// for forward compatibility.
//
// MeshControl is the service that manages the data plane proxies
// Control Plane implements this server
// Data Plane proxies are clients
type MeshControlServer interface {
	// StreamConfig establishes a long-lived connection between proxy and control plane
	// The proxy sends its info, and the control plane streams config updates
	// This is a SERVER STREAMING RPC - server sends multiple messages
	StreamConfig(*ProxyInfo, grpc.ServerStreamingServer[ConfigUpdate]) error
	// RegisterProxy allows a proxy to register itself with the control plane
	// This is a UNARY RPC - single request, single response
	RegisterProxy(context.Context, *ProxyInfo) (*RegistrationResponse, error)
	mustEmbedUnimplementedMeshControlServer()
}

// UnimplementedMeshControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshControlServer struct{}

func (UnimplementedMeshControlServer) StreamConfig(*ProxyInfo, grpc.ServerStreamingServer[ConfigUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamConfig not implemented")
}
func (UnimplementedMeshControlServer) RegisterProxy(context.Context, *ProxyInfo) (*RegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterProxy not implemented")
}
func (UnimplementedMeshControlServer) mustEmbedUnimplementedMeshControlServer() {}
func (UnimplementedMeshControlServer) testEmbeddedByValue()                     {}

// UnsafeMeshControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshControlServer will
// result in compilation errors.
type UnsafeMeshControlServer interface {
	mustEmbedUnimplementedMeshControlServer()
}

func RegisterMeshControlServer(s grpc.ServiceRegistrar, srv MeshControlServer) {
	// If the following call panics, it indicates UnimplementedMeshControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeshControl_ServiceDesc, srv)
}

func _MeshControl_StreamConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProxyInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshControlServer).StreamConfig(m, &grpc.GenericServerStream[ProxyInfo, ConfigUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshControl_StreamConfigServer = grpc.ServerStreamingServer[ConfigUpdate]

func _MeshControl_RegisterProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshControlServer).RegisterProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshControl_RegisterProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshControlServer).RegisterProxy(ctx, req.(*ProxyInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// MeshControl_ServiceDesc is the grpc.ServiceDesc for MeshControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeshControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mesh.MeshControl",
	HandlerType: (*MeshControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterProxy",
			Handler:    _MeshControl_RegisterProxy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConfig",
			Handler:       _MeshControl_StreamConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/mesh.proto",
}
