// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/mesh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProxyInfo contains information about a data plane proxy
type ProxyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyId       string                 `protobuf:"bytes,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`          // Unique ID for this proxy (e.g., "proxy-1", "events-proxy")
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                         // Proxy version (e.g., "1.0.0")
	ListenAddr    string                 `protobuf:"bytes,3,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"` // Address proxy is listening on (e.g., "0.0.0.0:8000")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyInfo) Reset() {
	*x = ProxyInfo{}
	mi := &file_api_proto_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyInfo) ProtoMessage() {}

func (x *ProxyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyInfo.ProtoReflect.Descriptor instead.
func (*ProxyInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyInfo) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *ProxyInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProxyInfo) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

// RegistrationResponse is sent when a proxy successfully registers
type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_api_proto_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ConfigUpdate contains routing configuration updates
// This is what the control plane sends to proxies
type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // Config version number (increments with each update)
	Routes        []*Route               `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`    // List of routing rules
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_api_proto_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigUpdate) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

// Route defines how to route requests
type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                      // Path pattern (e.g., "/api/users", "/api/events")
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`                                // Backend address (e.g., "localhost:3000", "users-service:5000")
	AuthRequired  bool                   `protobuf:"varint,3,opt,name=auth_required,json=authRequired,proto3" json:"auth_required,omitempty"` // Whether this route requires authentication
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`          // Request timeout in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_api_proto_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_api_proto_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *Route) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Route) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *Route) GetAuthRequired() bool {
	if x != nil {
		return x.AuthRequired
	}
	return false
}

func (x *Route) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

var File_api_proto_mesh_proto protoreflect.FileDescriptor

const file_api_proto_mesh_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/mesh.proto\x12\x04mesh\"a\n" +
	"\tProxyInfo\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\tR\aproxyId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vlisten_addr\x18\x03 \x01(\tR\n" +
	"listenAddr\"J\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\fConfigUpdate\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12#\n" +
	"\x06routes\x18\x02 \x03(\v2\v.mesh.RouteR\x06routes\"y\n" +
	"\x05Route\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12#\n" +
	"\rauth_required\x18\x03 \x01(\bR\fauthRequired\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs2\x82\x01\n" +
	"\vMeshControl\x125\n" +
	"\fStreamConfig\x12\x0f.mesh.ProxyInfo\x1a\x12.mesh.ConfigUpdate0\x01\x12<\n" +
	"\rRegisterProxy\x12\x0f.mesh.ProxyInfo\x1a\x1a.mesh.RegistrationResponseB)Z'github.com/SimonePesci/gomesh/api/protob\x06proto3"

var (
	file_api_proto_mesh_proto_rawDescOnce sync.Once
	file_api_proto_mesh_proto_rawDescData []byte
)

func file_api_proto_mesh_proto_rawDescGZIP() []byte {
	file_api_proto_mesh_proto_rawDescOnce.Do(func() {
		file_api_proto_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_mesh_proto_rawDesc), len(file_api_proto_mesh_proto_rawDesc)))
	})
	return file_api_proto_mesh_proto_rawDescData
}

var file_api_proto_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_mesh_proto_goTypes = []any{
	(*ProxyInfo)(nil),            // 0: mesh.ProxyInfo
	(*RegistrationResponse)(nil), // 1: mesh.RegistrationResponse
	(*ConfigUpdate)(nil),         // 2: mesh.ConfigUpdate
	(*Route)(nil),                // 3: mesh.Route
}
var file_api_proto_mesh_proto_depIdxs = []int32{
	3, // 0: mesh.ConfigUpdate.routes:type_name -> mesh.Route
	0, // 1: mesh.MeshControl.StreamConfig:input_type -> mesh.ProxyInfo
	0, // 2: mesh.MeshControl.RegisterProxy:input_type -> mesh.ProxyInfo
	2, // 3: mesh.MeshControl.StreamConfig:output_type -> mesh.ConfigUpdate
	1, // 4: mesh.MeshControl.RegisterProxy:output_type -> mesh.RegistrationResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_mesh_proto_init() }
func file_api_proto_mesh_proto_init() {
	if File_api_proto_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_mesh_proto_rawDesc), len(file_api_proto_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_mesh_proto_goTypes,
		DependencyIndexes: file_api_proto_mesh_proto_depIdxs,
		MessageInfos:      file_api_proto_mesh_proto_msgTypes,
	}.Build()
	File_api_proto_mesh_proto = out.File
	file_api_proto_mesh_proto_goTypes = nil
	file_api_proto_mesh_proto_depIdxs = nil
}
